### ISSUE TITLE
Make it feature Complet

### ISSUE THREAD

**Issue by frank-dspeed** [stealify/VSStudio#1]
## VSStudio
This is a mixture of best practices that we saw in the Open Source World that we Combined together into a usefully starter Application that can build it self with other components. 

It is a perfect example of what we create when we apply the build our self pattern with the stealify component system pattern. We Replace so many Applications and Feature Implementations with a single Software Product that is simple to Maintain even as a Single Developer it is able to get enrolled in Production. Something that was only possible with Extensive cloud provider or administration knowledge. 

- [ ] merge: vscodium build process
- [ ] merge: electron-compat for Handle based PeerConnections
- [ ] merge: code-server build process
- [ ] merge: @stealify/editor 
- [ ] merge: baker browser feature set
- [ ] merge: PeerConnection Recorder and Player 
- [ ] merge: Streaming Broadcaster interface for rtc-cluster/rtc-cluster
- [ ] merge: @stealify/webplatform 

## Goals 
Be the successor that is feature complet of the following products:
- vscode
- theia
- code-server
- baker-browser
- obs
- WPEWebKit 
- WebView2 
- Chromium Content 
- MOJO:IPC
- Couchbase
- Oracle Database
- Oracle GraalVM

**Comment by lemanschik** [comment]
partial archived and moved to: https://github.com/unlicense-code/editor/issues/25
